version: '3.1'
services:
  db:
    platform: linux/amd64
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crudapp
    ports:
      - "3308:3306"